// Bibliothèque pré-remplie des activités du calendrier annuel de l'agent comptable
// Sources : décret 2012-1246 (GBCP), art. R. 421-64 et s. Code éducation, M9.6,
// circulaire n° 2011-117 du 03/08/2011 (voyages), guides DAF A3 / IH2EF, vade-mecum

export type Periodicite = 'mensuelle' | 'trimestrielle' | 'annuelle' | 'ponctuelle';
export type Categorie =
  | 'Cloture / Inventaire'
  | 'Compte financier'
  | 'Bourses'
  | 'Voyages scolaires'
  | 'Budget'
  | 'Régies'
  | 'Contrôle interne'
  | 'Audit ER'
  | 'Pilotage / Conseil AC'
  | 'Restauration / SRH'
  | 'Recouvrement'
  | 'Marchés / Achats'
  | 'Ressources';

export interface ActiviteModele {
  id: string;
  titre: string;
  categorie: Categorie;
  periodicite: Periodicite;
  // Mois clé (1-12) pour l'affichage par défaut. Pour mensuel : 0 = tous les mois.
  moisDebut: number;
  moisFin?: number;
  reference?: string;
  description: string;
  responsable: 'AC' | 'ER' | 'AC+ER';
  criticite: 'haute' | 'moyenne' | 'info';
}

export const ACTIVITES_MODELES: ActiviteModele[] = [
  // ═══ JANVIER — Inventaire et clôture définitive ═══
  {
    id: 'jan-inventaire',
    titre: "Opérations d'inventaire sur exercice N-1 (date comptable 31/12/N-1)",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 1,
    reference: 'M9.6 — GBCP',
    description: "Apurement EJ, extourne charges à payer / produits à recevoir, liquidation définitive des factures, contre-passations, variations de stocks (DBM 293), amortissements, relevés de compteurs, inventaire denrées / matières / objets confectionnés / fuel / gaz.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'jan-dbm22-credit-nourriture',
    titre: "Variation du crédit nourriture (DBM 22) — service SRH",
    categorie: 'Restauration / SRH',
    periodicite: 'trimestrielle',
    moisDebut: 1,
    description: "À calculer quelques semaines avant la fin de chaque trimestre afin de vérifier si le solde permet de boucler les charges du trimestre.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },
  {
    id: 'jan-er-stocks-gti',
    titre: "Transmission par les ER : états de stocks au 31/12 et GTI (valeurs inactives)",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 1,
    description: "Tous documents nécessaires à l'inventaire à transmettre à l'AC sans retard.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'jan-cloture-21',
    titre: "Avant le 21 janvier : fin de toutes les opérations d'exercice N-1",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 1,
    description: "Date butoir réglementaire pour la finalisation des opérations de fin d'exercice N-1.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'jan-rappel-ej',
    titre: "Rappel SG : apurer régulièrement les EJ et opérations bloquantes",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 1,
    description: "Note de l'AC aux secrétaires généraux : prendre dès le début d'année l'habitude d'apurer les engagements juridiques pour ne pas bloquer le compte financier.",
    responsable: 'AC',
    criticite: 'moyenne',
  },

  // ═══ FÉVRIER — AVRIL — Compte financier ═══
  {
    id: 'fev-elaboration-cf',
    titre: "Élaboration du compte financier N-1",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 2,
    moisFin: 4,
    reference: 'art. R. 421-77 Code éducation',
    description: "Préparation du compte financier par l'agent comptable en lien avec les ordonnateurs.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'avr-vote-cf',
    titre: "Vote du compte financier au CA — au plus tard le 30 avril",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 4,
    reference: 'art. R. 421-77 Code éducation',
    description: "Avant expiration du 4ᵉ mois suivant le 31/12. AC présente la situation patrimoniale ; SG présente l'exécution budgétaire et le compte rendu de gestion.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'avr-fourniture-docs',
    titre: "Fourniture des documents post-CA par l'AC",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 4,
    description: "Juste après la séance de travail du CA, l'AC fournit les documents nécessaires.",
    responsable: 'AC',
    criticite: 'moyenne',
  },
  {
    id: 'avr-transmission-actes',
    titre: "Transmission des actes du CA — sous 30 jours après le vote",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 4,
    description: "Délai maximum de 30 jours après le vote du CA pour la transmission des actes.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'avr-controle-interne-diag',
    titre: "Contrôle interne comptable et financier — diagnostic",
    categorie: 'Contrôle interne',
    periodicite: 'annuelle',
    moisDebut: 4,
    moisFin: 5,
    description: "Diagnostic CICF en lien avec la cartographie des risques.",
    responsable: 'AC',
    criticite: 'moyenne',
  },

  // ═══ MAI — AOÛT ═══
  {
    id: 'mai-conseil-ac',
    titre: "Réunions du conseil de l'agence comptable",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 5,
    moisFin: 6,
    description: "Réunions de pilotage du groupement comptable.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },
  {
    id: 'mai-controle-regies',
    titre: "Contrôles des régies permanentes et temporaires",
    categorie: 'Régies',
    periodicite: 'annuelle',
    moisDebut: 5,
    moisFin: 7,
    reference: 'décret 2019-798',
    description: "Au moins une fois tous les 2 ans. Contrôle de la caisse, des pièces justificatives et des avances.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'jun-bourses-t3',
    titre: "Liquidation et paiement des bourses du 3ᵉ trimestre",
    categorie: 'Bourses',
    periodicite: 'annuelle',
    moisDebut: 6,
    description: "Généralement fin juin. AC paie et suit les comptes 441120 / 441912.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'jun-vote-programmation-voyages',
    titre: "Vote CA — programmation des voyages scolaires année scolaire suivante",
    categorie: 'Voyages scolaires',
    periodicite: 'annuelle',
    moisDebut: 6,
    moisFin: 7,
    reference: 'circ. n° 2011-117 du 03/08/2011',
    description: "Présentation et vote de la programmation des voyages au CA en juin ou juillet (anticipation exigée par la circulaire).",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'jul-verification-pre-conges',
    titre: "Vérification d'été — opérations en cours et EJ",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 7,
    description: "Vérification recommandée avant les congés des opérations en cours et apurement préventif des engagements juridiques.",
    responsable: 'AC',
    criticite: 'moyenne',
  },

  // ═══ SEPTEMBRE — Rentrée comptable ═══
  {
    id: 'sep-accreditation-ordonnateurs',
    titre: "Réception des arrêtés de nomination et accréditations des ordonnateurs",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 9,
    reference: 'arrêté du 25 juillet 2013',
    description: "Vérification des accréditations des ordonnateurs et délégations de signature.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'sep-transmission-calendrier',
    titre: "Transmission du calendrier annuel aux ER",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 9,
    description: "Diffusion du présent calendrier aux établissements rattachés lors du conseil de l'agence comptable.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'sep-conseil-ac-rentree',
    titre: "Réunion du conseil de l'agence comptable — rentrée",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 9,
    description: "Réunion de rentrée du conseil du groupement.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },
  {
    id: 'sep-organigramme-pa',
    titre: "Mise à jour organigramme fonctionnel et plan d'action CICF",
    categorie: 'Contrôle interne',
    periodicite: 'annuelle',
    moisDebut: 9,
    description: "Actualisation de l'organigramme fonctionnel et du plan d'action de maîtrise des risques.",
    responsable: 'AC',
    criticite: 'moyenne',
  },
  {
    id: 'sep-vote-financement-voyages',
    titre: "Vote CA — financement des voyages scolaires",
    categorie: 'Voyages scolaires',
    periodicite: 'annuelle',
    moisDebut: 9,
    moisFin: 10,
    reference: 'circ. n° 2011-117',
    description: "Vote du financement après la programmation. Prévoir ensuite la mise en concurrence (Code de la commande publique) et le délai pour le paiement des familles.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'sep-bourses-campagne',
    titre: "Démarrage campagne bourses (1ᵉʳ trimestre)",
    categorie: 'Bourses',
    periodicite: 'annuelle',
    moisDebut: 9,
    description: "Préparation de la liquidation du 1ᵉʳ trimestre et lancement de la campagne.",
    responsable: 'ER',
    criticite: 'moyenne',
  },
  {
    id: 'sep-er-concessions-stocks',
    titre: "ER : transmettre concessions de logement, inventaires stocks, projet de budget",
    categorie: 'Ressources',
    periodicite: 'annuelle',
    moisDebut: 9,
    description: "Documents indispensables à la préparation de l'exercice et du budget N+1.",
    responsable: 'ER',
    criticite: 'moyenne',
  },

  // ═══ OCTOBRE ═══
  {
    id: 'oct-note-fin-exercice',
    titre: "Note « opérations de fin d'exercice » envoyée par l'AC",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 10,
    description: "Instructions détaillées de clôture envoyées à tous les ER.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'oct-debut-apurement-ej',
    titre: "Début apurement des EJ — limiter les commandes non urgentes",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 10,
    description: "Apurement progressif des engagements juridiques en vue de la clôture. Limitation des commandes non urgentes dès mi-novembre.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'oct-bourses-fin-demandes',
    titre: "Campagne bourses : fin des demandes (3ᵉ jeudi d'octobre)",
    categorie: 'Bourses',
    periodicite: 'annuelle',
    moisDebut: 10,
    description: "Date limite réglementaire de dépôt des demandes de bourses.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'oct-point-trim-tresorerie',
    titre: "Point trimestriel trésorerie et créances",
    categorie: 'Recouvrement',
    periodicite: 'trimestrielle',
    moisDebut: 10,
    description: "Point trimestriel avec chaque ordonnateur sur la trésorerie, les créances et le délai global de paiement.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },

  // ═══ NOVEMBRE ═══
  {
    id: 'nov-notif-subvention',
    titre: "Notification de la subvention globale de la collectivité (avant 1ᵉʳ nov.)",
    categorie: 'Budget',
    periodicite: 'annuelle',
    moisDebut: 11,
    description: "Réception de la notification déclenchant l'élaboration du budget N+1.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'nov-ar-chef-etab',
    titre: "Accusé de réception par le chef d'établissement → délai 30j vote CA",
    categorie: 'Budget',
    periodicite: 'annuelle',
    moisDebut: 11,
    description: "L'AR déclenche le délai réglementaire de 30 jours pour le vote du budget au CA.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'nov-arret-commandes',
    titre: "Arrêt des commandes (dans la mesure du possible)",
    categorie: 'Marchés / Achats',
    periodicite: 'annuelle',
    moisDebut: 11,
    description: "Pour avoir toutes les factures payées avant la fin de l'exercice.",
    responsable: 'ER',
    criticite: 'moyenne',
  },

  // ═══ DÉCEMBRE — Clôture ═══
  {
    id: 'dec-arret-menues-depenses',
    titre: "Arrêt des menues dépenses (vers le 11 décembre)",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Arrêt des menues dépenses en vue de la clôture.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'dec-stop-tickets-repas',
    titre: "Stopper la vente des tickets repas (12-13 décembre)",
    categorie: 'Restauration / SRH',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Arrêt de la vente des tickets repas pour permettre l'arrêté des comptes.",
    responsable: 'ER',
    criticite: 'moyenne',
  },
  {
    id: 'dec-mandater-15',
    titre: "Mandater toutes factures et émettre tous titres avant le 15 décembre",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Sous Op@le : émission de toutes les demandes de paiement et titres de recette possibles avant la date butoir.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'dec-encaissement-final',
    titre: "Encaissement final des chèques",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Dernier dépôt et encaissement des chèques avant clôture.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'dec-bourses-t1',
    titre: "Liquidation et paiement des bourses du 1ᵉʳ trimestre",
    categorie: 'Bourses',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Généralement fin décembre.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'dec-prepa-cf',
    titre: "Préparation du compte financier N (inventaires au 31/12)",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Inventaires denrées, matières, objets confectionnés, fuel/gaz au 31/12.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'dec-cloture-regies',
    titre: "Clôture des régies temporaires et restitution des avances",
    categorie: 'Régies',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Clôture des régies temporaires de l'année et restitution de l'avance pour menues dépenses.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'dec-er-transmission-finale',
    titre: "ER : transmission de tous les éléments à l'AC (avant 15/12)",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Respect strict de la date pour permettre l'apurement et l'inventaire.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'dec-taxe-apprentissage',
    titre: "Campagne taxe d'apprentissage",
    categorie: 'Ressources',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Sollicitation des entreprises.",
    responsable: 'ER',
    criticite: 'moyenne',
  },

  // ═══ AVRIL — JUIN spécifique voyages ═══
  {
    id: 'avr-recensement-voyages',
    titre: "Recensement des projets de voyages scolaires",
    categorie: 'Voyages scolaires',
    periodicite: 'annuelle',
    moisDebut: 4,
    moisFin: 6,
    reference: 'circ. n° 2011-117 du 03/08/2011',
    description: "Remontée des projets par les ER en vue du vote de programmation au CA de juin ou juillet (année scolaire suivante).",
    responsable: 'ER',
    criticite: 'haute',
  },

  // ═══ JUIN — Compte financier sur Infocentre ═══
  {
    id: 'jun-cf-infocentre',
    titre: "Envoi du compte financier sur Infocentre — avant fin juin",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 6,
    description: "Délai de rigueur pour la transmission du compte financier sur Infocentre par l'agent comptable.",
    responsable: 'AC',
    criticite: 'haute',
  },

  // ═══ MARS — Bourses T2 ═══
  {
    id: 'mar-bourses-t2',
    titre: "Liquidation et paiement des bourses du 2ᵉ trimestre",
    categorie: 'Bourses',
    periodicite: 'annuelle',
    moisDebut: 3,
    description: "Généralement fin mars.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },

  // ═══ AUDITS ER — toute l'année ═══
  {
    id: 'audit-er-annuel',
    titre: "Audit AC dans chaque ER (au moins 1 fois / an)",
    categorie: 'Audit ER',
    periodicite: 'annuelle',
    moisDebut: 9,
    moisFin: 6,
    description: "Planifié en septembre (conseil de l'agence) et réalisé au moins une fois par an : contrôle de la comptabilité matière, des régies, des pièces justificatives, apurement des engagements.",
    responsable: 'AC',
    criticite: 'haute',
  },

  // ═══ MENSUEL ═══
  {
    id: 'mois-arret-comptes',
    titre: "Arrêt mensuel des comptes et édition des états",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'mensuelle',
    moisDebut: 0,
    description: "Arrêt mensuel des comptes et édition des états nécessaires. Les SG ont accès direct aux balances via Op@le.",
    responsable: 'AC',
    criticite: 'moyenne',
  },

  // ═══ ITEMS COMPLÉMENTAIRES (Chantier 1 — refonte) ═══

  // JANVIER — additions
  {
    id: 'jan-rattachement-cca-pca',
    titre: "Rattachement charges/produits N-1 (CCA / PCA)",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 1,
    reference: 'M9-6 § 4.3',
    description: "Charges constatées d'avance (CCA) et produits constatés d'avance (PCA) pour respecter le principe de rattachement à l'exercice.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'jan-reprise-resultats',
    titre: "Reprise des résultats N-1 en N",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 1,
    description: "Écritures d'à-nouveaux et reprise des résultats de l'exercice précédent.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'jan-dbm-report',
    titre: "Première DBM de l'exercice (report de crédits)",
    categorie: 'Budget',
    periodicite: 'annuelle',
    moisDebut: 1,
    reference: 'GBCP 2012-1246',
    description: "DBM de report de crédits permettant la continuité des opérations engagées.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },

  // FÉVRIER — additions
  {
    id: 'fev-arretes-bourses',
    titre: "Arrêtés de régularisation des bourses (collège/lycée)",
    categorie: 'Bourses',
    periodicite: 'annuelle',
    moisDebut: 2,
    description: "Régularisation des arrêtés bourses suite aux modifications d'effectifs et de quotités.",
    responsable: 'ER',
    criticite: 'moyenne',
  },
  {
    id: 'fev-declaration-taxe-app',
    titre: "Déclaration taxe d'apprentissage N-1",
    categorie: 'Ressources',
    periodicite: 'annuelle',
    moisDebut: 2,
    description: "Déclaration et reversement de la taxe d'apprentissage perçue sur l'exercice précédent.",
    responsable: 'AC',
    criticite: 'moyenne',
  },
  {
    id: 'fev-recouvrements-douteux',
    titre: "Point d'étape sur les recouvrements douteux",
    categorie: 'Recouvrement',
    periodicite: 'trimestrielle',
    moisDebut: 2,
    description: "Identification des créances douteuses, propositions de provisions ou d'admissions en non-valeur.",
    responsable: 'AC',
    criticite: 'moyenne',
  },

  // MARS — additions
  {
    id: 'mar-cf-drfip',
    titre: "Envoi du compte financier aux services de la DRFiP",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 3,
    description: "Transmission du compte financier à la DRFiP dans le cadre du contrôle hiérarchisé.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'mar-rapport-annuel-ac',
    titre: "Préparation du rapport annuel de l'agent comptable",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 3,
    description: "Rédaction du rapport annuel d'activité de l'agence comptable.",
    responsable: 'AC',
    criticite: 'moyenne',
  },
  {
    id: 'mar-rappro-trim',
    titre: "Rapprochement bancaire trimestriel",
    categorie: 'Contrôle interne',
    periodicite: 'trimestrielle',
    moisDebut: 3,
    description: "Rapprochement bancaire formalisé du trimestre, validation de l'absence d'écarts inexpliqués.",
    responsable: 'AC',
    criticite: 'haute',
  },

  // MAI — additions
  {
    id: 'mai-dob-prep',
    titre: "Préparation du débat d'orientation budgétaire (DOB)",
    categorie: 'Budget',
    periodicite: 'annuelle',
    moisDebut: 5,
    description: "Préparation du DOB qui précède le vote du budget primitif N+1.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },
  {
    id: 'mai-cartographie-update',
    titre: "Mise à jour de la cartographie des risques",
    categorie: 'Contrôle interne',
    periodicite: 'annuelle',
    moisDebut: 5,
    reference: 'M9-6 § 5.2',
    description: "Réévaluation annuelle des risques (probabilité × impact × maîtrise) sur les 11 processus Cartop@le.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'mai-supervision-niv2',
    titre: "Contrôle interne comptable : supervision de 2ᵉ niveau",
    categorie: 'Contrôle interne',
    periodicite: 'annuelle',
    moisDebut: 5,
    description: "Revue de second niveau par l'agent comptable des contrôles de premier niveau.",
    responsable: 'AC',
    criticite: 'moyenne',
  },

  // JUIN — additions
  {
    id: 'jun-cloture-pedago',
    titre: "Clôture pédagogique — préparation de la rentrée",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 6,
    description: "Anticipation des opérations de rentrée : tarifs DP, effectifs, dotations.",
    responsable: 'ER',
    criticite: 'moyenne',
  },
  {
    id: 'jun-relances-impayes',
    titre: "Campagne de relance des impayés avant fin d'exercice scolaire",
    categorie: 'Recouvrement',
    periodicite: 'annuelle',
    moisDebut: 6,
    description: "Relances familles avant les congés d'été pour limiter les pertes de contact.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },

  // JUILLET — additions
  {
    id: 'jul-arrete-comptes-3107',
    titre: "Arrêté des comptes au 31/07 (fin d'exercice pédagogique)",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 7,
    description: "Point intermédiaire à la fin de l'année scolaire pour cadrer la suite.",
    responsable: 'AC',
    criticite: 'moyenne',
  },
  {
    id: 'jul-bilan-voyages',
    titre: "Bilan des voyages scolaires de l'année",
    categorie: 'Voyages scolaires',
    periodicite: 'annuelle',
    moisDebut: 7,
    reference: 'circ. 2011-117',
    description: "Bilan financier et pédagogique des voyages réalisés, restitution éventuelle des excédents.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },
  {
    id: 'jul-fonds-sociaux-bilan',
    titre: "Point fonds sociaux : reliquat, reconduction",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 7,
    description: "Bilan d'utilisation des fonds sociaux (FSE, FSL) et anticipation de la reconduction N+1.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },

  // AOÛT — additions
  {
    id: 'aou-tarifs-dp',
    titre: "Préparation rentrée : tarifs DP, forfaits, ventilations",
    categorie: 'Restauration / SRH',
    periodicite: 'annuelle',
    moisDebut: 8,
    description: "Mise à jour des tarifs et ventilations en vue de la rentrée. Vote au CA en septembre.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },
  {
    id: 'aou-opale-rentree',
    titre: "Paramétrage Op@le pour la nouvelle année scolaire",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 8,
    description: "Paramétrages Op@le rentrée : exercices, tiers, signataires, habilitations.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'aou-delegations-signature',
    titre: "Vérification des délégations de signature (rentrée)",
    categorie: 'Pilotage / Conseil AC',
    periodicite: 'annuelle',
    moisDebut: 8,
    reference: 'arrêté 25 juillet 2013',
    description: "Vérification et renouvellement des délégations de signature avant la rentrée.",
    responsable: 'AC',
    criticite: 'haute',
  },

  // SEPTEMBRE — additions
  {
    id: 'sep-deliberation-fonds-sociaux',
    titre: "Délibération CA — modalités d'attribution des fonds sociaux (OBLIGATOIRE)",
    categorie: 'Contrôle interne',
    periodicite: 'annuelle',
    moisDebut: 9,
    reference: 'Code éducation + M9-6 — Circ. 2017-122',
    description: "Délibération obligatoire du CA sur les modalités d'attribution des fonds sociaux. Sans cette délibération, l'agent comptable ne peut valablement payer les aides.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'sep-vote-tarifs-dp',
    titre: "Vote des tarifs de la DP et de l'hébergement",
    categorie: 'Restauration / SRH',
    periodicite: 'annuelle',
    moisDebut: 9,
    reference: 'Code éducation R. 531-52',
    description: "Vote en CA des tarifs annuels de demi-pension et hébergement pour l'année scolaire en cours.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'sep-renouvellement-regies',
    titre: "Renouvellement des régies (arrêtés, IR)",
    categorie: 'Régies',
    periodicite: 'annuelle',
    moisDebut: 9,
    reference: 'décret 2019-798 ; Ord. 2022-408',
    description: "Renouvellement des arrêtés constitutifs et actes de nomination des régisseurs, vérification du versement de l'indemnité de responsabilité (IR) — le cautionnement est supprimé depuis le 1er janvier 2023 (Ord. 2022-408 + Décret 2022-1605).",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'sep-droits-dp',
    titre: "Constat des droits de demi-pension (transfert GFE → Op@le)",
    categorie: 'Restauration / SRH',
    periodicite: 'trimestrielle',
    moisDebut: 9,
    description: "Constat des droits de demi-pension, vérification des transferts GFE/SIECLE → Op@le.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },

  // OCTOBRE — additions
  {
    id: 'oct-prep-budget-n1',
    titre: "Préparation du budget primitif N+1",
    categorie: 'Budget',
    periodicite: 'annuelle',
    moisDebut: 10,
    description: "Préparation du budget primitif N+1 en vue du vote en novembre.",
    responsable: 'AC+ER',
    criticite: 'haute',
  },
  {
    id: 'oct-bilan-bourses-t1',
    titre: "Bilan des bourses (1ᵉʳ trimestre)",
    categorie: 'Bourses',
    periodicite: 'trimestrielle',
    moisDebut: 10,
    description: "Bilan post-liquidation du 1ᵉʳ trimestre des bourses.",
    responsable: 'ER',
    criticite: 'moyenne',
  },

  // NOVEMBRE — additions
  {
    id: 'nov-vote-budget',
    titre: "Vote du budget primitif N+1 en CA",
    categorie: 'Budget',
    periodicite: 'annuelle',
    moisDebut: 11,
    reference: 'art. R. 421-58 Code éducation',
    description: "Vote du budget primitif au CA dans les 30 jours après notification de la subvention.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'nov-transmission-budget',
    titre: "Transmission du budget aux autorités de contrôle",
    categorie: 'Budget',
    periodicite: 'annuelle',
    moisDebut: 11,
    description: "Transmission du budget voté au rectorat et à la collectivité de rattachement.",
    responsable: 'ER',
    criticite: 'haute',
  },
  {
    id: 'nov-engagements-report',
    titre: "Recensement des engagements à reporter",
    categorie: 'Compte financier',
    periodicite: 'annuelle',
    moisDebut: 11,
    description: "Identification des engagements juridiques à reporter sur l'exercice suivant.",
    responsable: 'AC+ER',
    criticite: 'moyenne',
  },
  {
    id: 'nov-inventaire-stocks',
    titre: "Inventaire des stocks denrées et fournitures",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 11,
    description: "Inventaire physique des stocks de denrées et fournitures avant clôture.",
    responsable: 'ER',
    criticite: 'haute',
  },

  // DÉCEMBRE — additions
  {
    id: 'dec-apurement-attente',
    titre: "Apurement des comptes d'attente (C/47, C/46)",
    categorie: 'Cloture / Inventaire',
    periodicite: 'annuelle',
    moisDebut: 12,
    reference: 'M9-6',
    description: "Apurement obligatoire des comptes d'attente (471, 472, 473, 486, 487) avant clôture.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'dec-rappro-bancaire-final',
    titre: "Dernier rapprochement bancaire de l'année",
    categorie: 'Contrôle interne',
    periodicite: 'annuelle',
    moisDebut: 12,
    description: "Rapprochement bancaire formalisé du 31/12 — pré-requis du compte financier.",
    responsable: 'AC',
    criticite: 'haute',
  },
  {
    id: 'dec-pv-caisse-3112',
    titre: "PV de caisse au 31/12",
    categorie: 'Régies',
    periodicite: 'annuelle',
    moisDebut: 12,
    reference: 'décret 2019-798',
    description: "Procès-verbal de caisse du 31/12 pour chaque régie de recettes et d'avances.",
    responsable: 'AC',
    criticite: 'haute',
  },
];

export const CATEGORIES_COULEURS: Record<Categorie, string> = {
  'Cloture / Inventaire': 'bg-red-100 text-red-900 border-red-300',
  'Compte financier': 'bg-orange-100 text-orange-900 border-orange-300',
  'Bourses': 'bg-amber-100 text-amber-900 border-amber-300',
  'Voyages scolaires': 'bg-sky-100 text-sky-900 border-sky-300',
  'Budget': 'bg-emerald-100 text-emerald-900 border-emerald-300',
  'Régies': 'bg-violet-100 text-violet-900 border-violet-300',
  'Contrôle interne': 'bg-indigo-100 text-indigo-900 border-indigo-300',
  'Audit ER': 'bg-rose-100 text-rose-900 border-rose-300',
  'Pilotage / Conseil AC': 'bg-slate-100 text-slate-900 border-slate-300',
  'Restauration / SRH': 'bg-lime-100 text-lime-900 border-lime-300',
  'Recouvrement': 'bg-yellow-100 text-yellow-900 border-yellow-300',
  'Marchés / Achats': 'bg-teal-100 text-teal-900 border-teal-300',
  'Ressources': 'bg-stone-100 text-stone-900 border-stone-300',
};

export const MOIS_NOMS = [
  'Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin',
  'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre',
];

export const MOIS_NOMS_COURT = ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'];
